import * as Sequelize from 'sequelize'

export default {
  up: (queryInterface: Sequelize.QueryInterface) => {
    return queryInterface.bulkInsert('appointments', [
      {
        idAppointment: 1,
        idPatientFisioterapist: 1,
        status: "Realizada",
        date: new Date(),
        time: "10:00",
        activies: "Exercícios Regulares",
        comments: "Prática realizada com sucesso",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idAppointment: 2,
        idPatientFisioterapist: 1,
        status: "Agendada",
        date: new Date(),
        time: "10:00",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idAppointment: 3,
        idPatientFisioterapist: 1,
        status: "Realizada",
        date: new Date(),
        time: "10:00",
        activies: "Exercícios Regulares",
        comments: "Prática realizada com sucesso",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idAppointment: 4,
        idPatientFisioterapist: 1,
        status: "Realizada",
        date: new Date(),
        time: "10:00",
        activies: "Exercícios Regulares",
        comments: "Prática realizada com sucesso",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idAppointment: 5,
        idPatientFisioterapist: 1,
        status: "Realizada",
        date: new Date(),
        time: "10:00",
        activies: "Exercícios Regulares",
        comments: "Prática realizada com sucesso",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idAppointment: 6,
        idPatientFisioterapist: 1,
        status: "Realizada",
        date: new Date(),
        time: "10:00",
        activies: "Exercícios Regulares",
        comments: "Prática realizada com sucesso",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idAppointment: 7,
        idPatientFisioterapist: 1,
        status: "Realizada",
        date: new Date(),
        time: "10:00",
        activies: "Exercícios Regulares",
        comments: "Prática realizada com sucesso",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idAppointment: 8,
        idPatientFisioterapist: 1,
        status: "Realizada",
        date: new Date(),
        time: "10:00",
        activies: "Exercícios Regulares",
        comments: "Prática realizada com sucesso",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idAppointment: 9,
        idPatientFisioterapist: 1,
        status: "Realizada",
        date: new Date(),
        time: "10:00",
        activies: "Exercícios Regulares",
        comments: "Prática realizada com sucesso",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idAppointment: 10,
        idPatientFisioterapist: 1,
        status: "Realizada",
        date: new Date(),
        time: "10:00",
        activies: "Exercícios Regulares",
        comments: "Prática realizada com sucesso",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ])
  },
  down: (queryInterface: Sequelize.QueryInterface) => {
    return queryInterface.bulkDelete('appointments', {})
  },
}
