import * as Sequelize from 'sequelize'

export default {
  up: (queryInterface: Sequelize.QueryInterface) => {
    return queryInterface.bulkInsert('calendars', [
      {
        idCalendar: 1,
        idFisioterapist: 1,
        available: "Livre",
        date: '2024-01-10',
        time: "10:00",
        duration: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCalendar: 2,
        idFisioterapist: 1,
        available: "Livre",
        date: '2024-01-10',
        time: "09:00",
        duration: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCalendar: 3,
        idFisioterapist: 1,
        available: "Livre",
        date: '2024-01-10',
        time: "11:00",
        duration: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCalendar: 4,
        idFisioterapist: 1,
        available: "Livre",
        date: '2024-01-10',
        time: "13:00",
        duration: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCalendar: 5,
        idFisioterapist: 1,
        available: "Livre",
        date: '2024-01-10',
        time: "14:00",
        duration: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCalendar: 6,
        idFisioterapist: 2,
        available: "Livre",
        date: '2024-01-10',
        time: "15:00",
        duration: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCalendar: 7,
        idFisioterapist: 1,
        available: "Livre",
        date: '2024-01-11',
        time: "09:00",
        duration: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCalendar: 8,
        idFisioterapist: 1,
        available: "Livre",
        date: '2024-01-11',
        time: "10:00",
        duration: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCalendar: 9,
        idFisioterapist: 1,
        available: "Livre",
        date: '2024-01-11',
        time: "11:00",
        duration: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCalendar: 10,
        idFisioterapist: 1,
        available: "Livre",
        date: '2024-01-11',
        time: "13:00",
        duration: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCalendar: 11,
        idFisioterapist: 2,
        available: "Livre",
        date: '2024-01-11',
        time: "14:00",
        duration: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCalendar: 12,
        idFisioterapist: 1,
        available: "Livre",
        date: '2024-01-11',
        time: "15:00",
        duration: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ])
  },
  down: (queryInterface: Sequelize.QueryInterface) => {
    return queryInterface.bulkDelete('calendars', {})
  },
}
