import * as Sequelize from 'sequelize'

export default {
  up: (queryInterface: Sequelize.QueryInterface) => {
    return queryInterface.bulkInsert('appointments', [
      {
        idAppointment: 1,
        idPatientFisioterapist: 1,
        status: "Realizada",
        idCalendar: 1,
        activies: "Exercícios Regulares",
        comments: "Prática realizada com sucesso",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idAppointment: 2,
        idPatientFisioterapist: 1,
        status: "Agendada",
        idCalendar: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idAppointment: 3,
        idPatientFisioterapist: 1,
        status: "Realizada",
        idCalendar: 3,
        activies: "Exercícios Regulares",
        comments: "Prática realizada com sucesso",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idAppointment: 4,
        idPatientFisioterapist: 1,
        status: "Realizada",
        idCalendar: 4,
        activies: "Exercícios Regulares",
        comments: "Prática realizada com sucesso",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idAppointment: 5,
        idPatientFisioterapist: 1,
        status: "Realizada",
        idCalendar: 5,
        activies: "Exercícios Regulares",
        comments: "Prática realizada com sucesso",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idAppointment: 6,
        idPatientFisioterapist: 1,
        status: "Realizada",
        idCalendar: 6,
        activies: "Exercícios Regulares",
        comments: "Prática realizada com sucesso",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idAppointment: 7,
        idPatientFisioterapist: 1,
        status: "Realizada",
        idCalendar: 7,
        activies: "Exercícios Regulares",
        notes: "Paciente com comportamento complicado",
        comments: "Prática realizada com sucesso",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idAppointment: 8,
        idPatientFisioterapist: 1,
        status: "Realizada",
        idCalendar: 8,
        activies: "Exercícios Regulares",
        comments: "Prática realizada com sucesso",
        notes: "Paciente Social",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idAppointment: 9,
        idPatientFisioterapist: 1,
        status: "Realizada",
        idCalendar: 9,
        activies: "Exercícios Regulares",
        comments: "Prática realizada com sucesso",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idAppointment: 10,
        idPatientFisioterapist: 1,
        status: "Realizada",
        idCalendar: 10,
        activies: "Exercícios Regulares",
        comments: "Prática realizada com sucesso",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ])
  },
  down: (queryInterface: Sequelize.QueryInterface) => {
    return queryInterface.bulkDelete('appointments', {})
  },
}
